### ISSUE TITLE
Remember birthday command

### ISSUE THREAD

**Issue by sanghin** [sanghin/feely#4]
We want to have the possibility to ask Feely to remember us birthday date. Feely will send a message in the general channel on the birthday date at the given hour. It will mark all peeps that are in the "notified" list (using a @ ).

Command to use:

`f!rbd NAME DATE HOUR PERSON_TO_NOTIFIED`

All command parameters are **required**.

- **f!** : prefix use to "talk" with Feely
- **rbd**: the command executed by Feely
- **NAME**: name of the person we want to remember the birthday
- **DATE**; birthday date. (format DD/MM/AAAA)
- **HOUR**: the hour we want to be alert at. (format HH:MM)
- **PERSON_TO_NOTIFIED**: users to notify (can be a list of members or only 1 member)

e.g;

`f!rdb The Goat 26/12/1988 10h15 ltribolet`

Feely will send this message in the general channel every year on the 26/12 at 10h15:

> @splio-tribolet it's The Goat birthday today (28 years)

**Comment by splio-ltribolet** [comment]
This is just a regular reminder function.

So break it down into a reminder function. then we could override it with a birthday reminder special, with some images and/or emojis for the occasion.

**Comment by sanghin** [comment]
I had this in mind :

- a "private" reminder method.
- a reminderBirthday function that call the reminder function with the appropriates parameters.

**Comment by ltribolet** [comment]
> This is just a regular reminder function.

> So break it down into a reminder function. then we could override it with a birthday reminder special, with some images and/or emojis for the occasion.

Created with wrong account before
